version: '3'
services:
  calculator-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_HOST: http://localhost:3001/truenorth
    ports:
      - 3000:3000
      